### ISSUE TITLE
Can't update from 2.04 to 2.05

### ISSUE THREAD

**Issue by bgaebel** [tanglebay/swarm-releases#1]
Hello,
when I open SWARM in my VPS an info pops up:
"Welcome to SWARM! [2.0.4]
A new version of SWARM (2.0.5) is available!
Do you want to update SWARM now?"

When I click on "Yes" the program crashes and jumps back to the command line of my VPS.
Due to this error no new line in den log file is created.

Interestingly the log file shows, that it allready has been updated to version 2.0.5

03-05-2022 09-20-01 [WACHTDOG] GOSHIMMER node was restarted because the service is not active.
03-05-2022 13-40-14 [xxxxxxxx] New version (2.0.0) of SWARM installed.
03-05-2022 21-30-06 [xxxxxxxx] New version (2.0.1) of SWARM installed.
06-05-2022 16-57-17 [AUTOUPDATE] New version (0.8.13) of GoShimmer installed and GoShimmer restarted.
08-05-2022 00-01-02 [WACHTDOG] WASP node was restarted because the service is not active.
08-05-2022 00-01-03 [WACHTDOG] HORNET node restarted because max milestones difference reached.
08-05-2022 00-02-01 [WACHTDOG] HORNET node was restarted because the service is not active.
08-05-2022 00-03-01 [WACHTDOG] HORNET node was restarted because the service is not active.
08-05-2022 00-04-01 [WACHTDOG] HORNET mainnetDB deleted because the maximum number of attempted restarts was reached.
08-05-2022 00-03-01 [WACHTDOG] HORNET node was restarted because the service is not active.
08-05-2022 00-04-01 [WACHTDOG] HORNET mainnetDB deleted because the maximum number of attempted restarts was reached.
08-05-2022 00-04-01 [WACHTDOG] HORNET node was restarted because the service is not active.
08-05-2022 21-25-08 [xxxxxxxx] New version (2.0.2) of SWARM installed.
08-05-2022 21-25-09 [WACHTDOG] HORNET node restarted because max milestones difference reached.
10-05-2022 19-50-04 [xxxxxxxx] New version (2.0.3) of SWARM installed.
15-05-2022 00-01-03 [WACHTDOG] HORNET node was restarted because the service is not active.
15-05-2022 00-01-03 [WACHTDOG] GOSHIMMER node was restarted because the service is not active.
15-05-2022 00-01-03 [WACHTDOG] WASP node was restarted because the service is not active.
16-05-2022 15-10-21 [AUTOUPDATE] New version (0.8.14) of GoShimmer installed and GoShimmer restarted.
19-05-2022 17-10-06 [xxxxxxxx] New version (2.0.4) of SWARM installed.
21-05-2022 20-00-02 [xxxxxxxx] New version (2.0.5) of SWARM installed.
22-05-2022 00-01-05 [WACHTDOG] HORNET node was restarted because the service is not active.
22-05-2022 00-01-05 [WACHTDOG] GOSHIMMER node was restarted because the service is not active.
22-05-2022 00-01-05 [WACHTDOG] WASP node was restarted because the service is not active.

Also my node (hornet&bee) crashes very often and the GoShimmer node can not sync with the network.

**Comment by no8ody** [comment]
Since version 2.0.4 an authentication is necessary for the installation/update of SWARM.
Under the following link (https.//tanglebay.com/swarm) you can find more information.

If and how long SWARM will be available for the community is still unclear.
